---
name: .dotfiles main
# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]

jobs:
  check:
    if: github.ref == 'refs/heads/main'
    name: check'n'test
    runs-on: ubuntu-latest
    env:
      DOTFILES_CI: 'true'
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-5|${{ hashFiles('uv.lock') }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: uv run alias check

  url-check:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Verify url shortener is pointing to latest setup.sh
        run: |
          GITHUB_URL="https://raw.githubusercontent.com/tkk2112/dotfiles/refs/heads/main/setup.sh"
          CUSTOM_URL="https://link.m04r.space/dotfiles"

          # Get content from both URLs
          GITHUB_CONTENT=$(curl -Ls "$GITHUB_URL")
          GITHUB_CHECKSUM=$(curl -Ls "$GITHUB_URL" | sha256sum | cut -d' ' -f1)
          CUSTOM_CHECKSUM=$(curl -Ls "$CUSTOM_URL" | sha256sum | cut -d' ' -f1)

          echo "Comparing checksums:"
          echo "GitHub ($GITHUB_URL): $GITHUB_CHECKSUM"
          echo "Custom ($CUSTOM_URL): $CUSTOM_CHECKSUM"

          if [ "$GITHUB_CHECKSUM" != "$CUSTOM_CHECKSUM" ]; then
            echo "Error: Custom URL content checksum differs from GitHub URL content checksum"
            exit 1
          fi

  sanity-check:
    needs: check
    if: github.ref == 'refs/heads/main'
    name: ${{ matrix.task.name }} on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.runner }}
    strategy:
      matrix:
        os:
          - name: ubuntu:LTS
            runner: ubuntu-latest
            image: jrei/systemd-ubuntu:24.04
        task:
          - name: workstation
            enable_sudo: 'true'
    container:
      image: ${{ matrix.os.image || '' }}
      options: ${{ matrix.os.options || '--privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro' }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Setup and run dotfiles
        uses: ./.github/actions/setup-and-run-dotfiles
        with:
          pkgs: 'git curl sudo'
          setup_args: ${{ matrix.task.setup_args }}
          task_name: ${{ matrix.task.name }}
          enable_sudo: ${{ matrix.task.enable_sudo }}

  test:
    if: always() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [sanity-check]
    steps:
      - run: exit 1
        if: ${{ contains(toJSON(needs.*.result), 'failure') || contains(toJSON(needs.*.result), 'cancelled') }}
